from hw1.main import Matrix

matrix = Matrix((10, 10), list(range(0, 100)))
print(matrix.__repr__())
print(matrix)
print(matrix[1,1])
print(matrix[1])
print(matrix[-1])
print(matrix[1:4])
print(matrix[:4])
print(matrix[4:])
print(matrix[:])
print(matrix[1:7:2])
print(matrix[:, 1])
print(matrix[1:4, 1:4])
print(matrix[1:4, :4])
print(matrix[1:4, 4:])
print(matrix[1:4, :])
print(matrix[-1:])
print(matrix[-2::-2])
print(matrix[-2::-2, 1:4])
print(matrix[:, :])
print(matrix[[1, 4]])
print(matrix[:, [1, 4]])
print(matrix[[1, 4], [1, 4]])
